// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://tktnajddgvfygbtvxaco.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InRrdG5hamRkZ3ZmeWdidHZ4YWNvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyNDM2ODcsImV4cCI6MjA3MjgxOTY4N30.T2zVbmJ8yVUfk6GrE1y-t_TPRBSOV7-9I8NZWddbXWI";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});